### Reset state before starting tests
POST http://localhost:8888/reset
# 200 OK

### Get balance for non-existing account
POST http://localhost:8888/balance?account_id=1234
# 404 0

### Create account with initial balance
POST http://localhost:8888/event
# 201 {"destination": {"id":"100", "balance":10}}
Content-Type: application/json

{"type":"deposit", "destination":"100", "amount":10}

### Deposit into existing account
POST http://localhost:8888/event
# 201 {"destination": {"id":"100", "balance":20}}
Content-Type: application/json

{"type":"deposit", "destination":"100", "amount":10}

### Get balance for existing account
GET http://localhost:8888/balance?account_id=100
# 200 20

### Withdraw from non-existing account
POST http://localhost:8888/event
# 404 0
Content-Type: application/json

{"type":"withdraw", "origin":"200", "amount":10}

### Withdraw from existing account
POST http://localhost:8888/event
# 201 {"origin": {"id":"100", "balance":15}}
Content-Type: application/json

{"type":"withdraw", "origin":"100", "amount":5}

### Transfer from existing account
POST http://localhost:8888/event
# 201 {"origin": {"id":"100", "balance":0}, "destination": {"id":"300", "balance":15}}
Content-Type: application/json

{"type":"transfer", "origin":"100", "amount":15, "destination":"300"}

### Transfer from non-existing account
POST http://localhost:8888/event
# 404 0
Content-Type: application/json

{"type":"transfer", "origin":"200", "amount":15, "destination":"300"}
